version: 0.2
phases:
  build:
    commands:
      - echo "Nothing to build..."
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync web/ s3://leads.mc.keycore.cloud --delete
